---
abstract: 'Apache Kafka low-level synchronous API, which does not use Zookeeper.'
author:
  - 'TrackingSoft LLC <sgladkov@trackingsoft.com>'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.132830, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Kafka
no_index:
  directory:
    - t
    - inc
    - xt
    - tools
provides:
  Kafka:
    file: lib/Kafka.pm
    version: '1.001013'
  Kafka::Connection:
    file: lib/Kafka/Connection.pm
    version: '1.001013'
  Kafka::Consumer:
    file: lib/Kafka/Consumer.pm
    version: '1.001013'
  Kafka::Exceptions:
    file: lib/Kafka/Exceptions.pm
    version: '1.001013'
  Kafka::IO:
    file: lib/Kafka/IO.pm
    version: '1.001013'
  Kafka::Int64:
    file: lib/Kafka/Int64.pm
    version: '1.001013'
  Kafka::Internals:
    file: lib/Kafka/Internals.pm
    version: '1.001013'
  Kafka::Message:
    file: lib/Kafka/Message.pm
    version: '1.001013'
  Kafka::Producer:
    file: lib/Kafka/Producer.pm
    version: '1.001013'
  Kafka::Protocol:
    file: lib/Kafka/Protocol.pm
    version: '1.001013'
requires:
  Carp: '1.08'
  Compress::Snappy: '0.23'
  Const::Fast: '0.014'
  Data::Compare: '1.24'
  Data::Validate::Domain: '0.11'
  Data::Validate::IP: '0.24'
  Exception::Class: '1.37'
  Exporter: '5.62'
  IO::Compress::Gzip: '2.008'
  IO::Select: '1.17'
  IO::Uncompress::Gunzip: '2.008'
  List::Util: '1.19'
  Params::Util: '1.07'
  Scalar::Util: '1.19'
  Scalar::Util::Numeric: '0.22'
  Socket: '1.30_01'
  String::CRC32: '1.5'
  Sys::SigAction: '0.21'
  Time::HiRes: '1.9711'
  Try::Tiny: '0.21'
  perl: '5.010'
version: '1.001013'
resources:
  bugtracker: https://github.com/TrackingSoft/Kafka/issues
  homepage: https://github.com/TrackingSoft/Kafka
  repository: git://github.com/TrackingSoft/Kafka.git
test_requires:
  Capture::Tiny: '0.24'
  Carp: '1.08'
  Clone: '0.36'
  Config::IniFiles: '2.83'
  Const::Fast: '0.014'
  Cwd: '3.2501'
  Data::Dumper: '2.121_14'
  Exporter: '5.62'
  File::HomeDir: '1.00'
  File::Path: '2.04'
  File::Spec: '3.2501'
  File::Spec::Functions: '3.2501'
  IO::File: '1.14'
  IO::Socket::INET: '1.31'
  IO::Socket::IP: '0.37'
  List::Util: '1.19'
  Net::EmptyPort: '0'
  Params::Util: '1.07'
  Proc::Daemon: '0.14'
  Proc::ProcessTable: '0.51'
  Scalar::Util: '1.19'
  Scalar::Util::Numeric: '0.22'
  Socket: '2.020'
  Sub::Install: '0.927'
  Sys::SigAction: '0.21'
  Test::Deep: '0.119'
  Test::Exception: '0.32'
  Test::More: '0.72'
  Test::NoWarnings: '1.04'
  Test::TCP: '2.08'
  Time::HiRes: '1.9711'
  Try::Tiny: '0.21'
